### ISSUE TITLE
Missing Libs and error on upload image

### ISSUE THREAD

**Issue by xelaz** [AlastairTaft/draft-js-editor#9]
I tried your example but at first i get error on missing packages draft-js,react,react-dom.
Please add it to the package.json

After install packages i get next error on upload image "Cannot read property 'wrapper' of undefined"

**Comment by AlastairTaft** [comment]
Those missing libs were setup as peer dependencies, while it broke the examples, it should still of worked as a third party package. I've added them as dev dependencies now so the examples should work without you having to install the missing packages manually.

I finally figured out that error you were getting was related to the 'code' block option. I've removed that option for now. While I appreciate this isn't really a fix I plan on refactoring the way those buttons work soon so that those options are pluggable like I've done so far with the pop over buttons.

Thanks for the report.

**Comment by AlastairTaft** [comment]
The error also existing on the image button. I've removed that for now, soon to add a way to make those buttons pluggable.

Focusing on making what's there work solidly at the moment.
